pipeline {
    agent any

    environment {
        PYTHON_SCRIPT = '--version'
        ONE_PRESS_FUNCTIONS_REPO_URL = 'https://github.com/BigCat3997/one-press-functions'
        ONE_PRESS_RESOURCES_REPO_URL = 'https://github.com/BigCat3997/one-press-resources'
        MAVEN_SIMPLE_API_REPO_URL = 'https://github.com/BigCat3997/maven-simple-api'
        CONDA_BIN_PATH = '/opt/miniconda3/bin/'
    }

    stages {
        stage('Bootstrap') {
            steps {
                script {
                    dir('one-press-functions') {
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: '*/main']],
                            userRemoteConfigs: [[url: env.ONE_PRESS_FUNCTIONS_REPO_URL]]
                        ])
                    }
                    dir('one-press-resources') {
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: '*/main']],
                            userRemoteConfigs: [[url: env.ONE_PRESS_RESOURCES_REPO_URL]]
                        ])
                    }
                    dir('maven-simple-api') {
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: '*/main']],
                            userRemoteConfigs: [[url: env.MAVEN_SIMPLE_API_REPO_URL]]
                        ])
                    }
                }
                sh '''
                    // echo "##vso[task.setvariable variable=PATH;]${CONDA_BIN_PATH}:${PATH}"
                    // echo "##vso[task.setvariable variable=PYTHONPATH;]${FUNCTIONS_WORK_DIR}:${PYTHONPATH}"
                    export PATH=${CONDA_BIN_PATH}:${PATH}
                    // export PYTHONPATH=${FUNCTIONS_WORK_DIR}:${PYTHONPATH}
                    conda activate one-press-functions
                    pwd
                    ls -lah
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                    ls -lah
                '''
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
                // sh 'touch "a.txt"'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
            archiveArtifacts artifacts: 'a.txt', fingerprint: true
        }
    }
}
