pipeline {
    agent { label 'debian-docker-agent1' }

    environment {
        PYTHON_SCRIPT = '--version'
        ONE_PRESS_FUNCTIONS_REPO_URL = 'https://github.com/BigCat3997/one-press-functions'
        ONE_PRESS_RESOURCES_REPO_URL = 'https://github.com/BigCat3997/one-press-resources'
        MAVEN_SIMPLE_API_REPO_URL = 'https://github.com/BigCat3997/maven-simple-api'
        CONDA_BIN_PATH = '/opt/miniconda3/bin'
        PATH = "${CONDA_BIN_PATH}:${env.PATH}"
        FUNCTIONS_WORK_DIR = "${WORKSPACE}/one-press-functions"
        PYTHONPATH = "${FUNCTIONS_WORK_DIR}:${PYTHONPATH}"
    }

    stages {
        stage('Bootstrap') {
            environment {
                PYTHON_SCRIPT = '--version'
                ONE_PRESS_FUNCTIONS_REPO_URL = 'https://github.com/BigCat3997/one-press-functions'
                ONE_PRESS_RESOURCES_REPO_URL = 'https://github.com/BigCat3997/one-press-resources'
                MAVEN_SIMPLE_API_REPO_URL = 'https://github.com/BigCat3997/maven-simple-api'
                SET_UP_STAGE_ADO_COMMAND = "${FUNCTIONS_WORK_DIR}/app/main.py SET_UP_STAGE_ADO"
            // CONDA_BIN_PATH = '/opt/miniconda3/bin'
            // EXECUTE_COMMAND= ${{ parameters.functionsWorkDir }}/app/main.py SET_UP_STAGE_ADO
            // EXECUTE_COMMAND= ${{ parameters.functionsWorkDir }}/app/main.py GIT_CLONE_ADO
            // EXECUTE_COMMAND= ${{ parameters.functionsWorkDir }}/app/main.py OVERRIDE_BUILD_NUMBER_ADO
            // EXECUTE_COMMAND= ${{ parameters.functionsWorkDir }}/app/main.py WRITE_DIARY
            }
            steps {
                script {
                    dir('one-press-functions') {
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: '*/main']],
                            userRemoteConfigs: [[url: env.ONE_PRESS_FUNCTIONS_REPO_URL]]
                        ])
                    }
                    dir('one-press-resources') {
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: '*/main']],
                            userRemoteConfigs: [[url: env.ONE_PRESS_RESOURCES_REPO_URL]]
                        ])
                    }
                    dir('maven-simple-api') {
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: '*/main']],
                            userRemoteConfigs: [[url: env.MAVEN_SIMPLE_API_REPO_URL]]
                        ])
                    }
                }
                sh '''#!/bin/bash
                    source activate one-press-functions
                    python --version
                    env
                    pwd
                    tree .
                    python $SET_UP_STAGE_ADO_COMMAND
                '''

            //               - bash: |
            //   source activate $FUNCTIONS_VENV
            //   python $EXECUTE_COMMAND
            // env:
            //   FUNCTIONS_VENV: ${{ parameters.functionsVenv }}
            //   EXECUTE_COMMAND: ${{ parameters.functionsWorkDir }}/app/main.py SET_UP_STAGE_ADO
            //   STAGE_NAME: BOOTSTRAP
            //   BOOTSTRAP_PREFIX_PATH: "${{ parameters.workspaceWorkDir }}"
            // displayName: "Bootstrap: Set up stage"
            }
        }

        stage('Build') {
            steps {
                sh '''
                    source activate one-press-functions
                    python --version
                    ls -lah
                '''
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            // sh 'touch "a.txt"'
            }
        }
    }

    // post {
    //     always {
    //         echo 'Pipeline finished.'
    //         archiveArtifacts artifacts: 'a.txt', fingerprint: true
    //     }
    // }
}
