pipeline {
    agent { label 'debian-docker-agent1' }

    parameters {
        string(name: 'gitBranch', defaultValue: 'main', description: 'Target branch.')
    }

    environment {
        ONE_PRESS_RESOURCES_REPO_URL = 'https://github.com/BigCat3997/one-press-resources'
        ONE_PRESS_BASH_REPO_URL = 'https://github.com/BigCat3997/one-press-bash'
        MAVEN_SIMPLE_API_REPO_URL = 'https://github.com/BigCat3997/maven-simple-api'
        GLOBAL_ENV_VAR_DIR = "${env.WORKSPACE}"
    }

    stages {
        stage('Bootstrap') {
            steps {
                script {
                    dir('one-press-resources') {
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: 'main']],
                            userRemoteConfigs: [[url: env.ONE_PRESS_RESOURCES_REPO_URL]]
                        ])
                    }
                    dir('one-press-bash') {
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: 'feature/init-phrase']],
                            userRemoteConfigs: [[url: env.ONE_PRESS_BASH_REPO_URL]]
                        ])
                    }

                    withEnv([
                        'STAGE_NAME=BOOTSTRAP',
                        "BOOTSTRAP_BASE_DIR=${env.WORKSPACE}",
                        // "GLOBAL_ENV_VAR_DIR=${env.GLOBAL_ENV_VAR_DIR}",
                    ]) {
                        dir('one-press-bash') {
                            // sh 'env'
                            sh './src/functions/initialize_workspace.sh'
                        }
                    }

                    withEnv([
                        "APP_SOURCE_BASE_DIR=${env.WORKSPACE}",
                        "GIT_URL=${env.MAVEN_SIMPLE_API_REPO_URL}",
                        "GIT_BRANCH=${params.gitBranch}",
                    ]) {
                        dir('one-press-bash') {
                            sh """
                            #!/bin/bash
                            set -e
                            chmod +x ${env.GLOBAL_ENV_VAR_DIR}/.env
                            source ${env.GLOBAL_ENV_VAR_DIR}/.env
                            ./src/functions/git_clone.sh
                            """
                        }
                    }

                    withEnv([
                        "PUBLISH_PREFIX_PATH=${env.WORKSPACE}/bootstrap_section",
                        "GIT_URL=${env.MAVEN_SIMPLE_API_REPO_URL}",
                        "PIPELINE_NAME=${env.JOB_NAME}",
                        "BUILD_NUMBER=${env.BUILD_NUMBER}",
                        "IS_IMAGE_TAG_BASED_ON_ENV=false"
                    ]) {
                        dir('one-press-bash') {
                            sh """
                            #!/bin/bash
                            set -e
                            chmod +x ${env.PUBLISH_PREFIX_PATH}/.env
                            source ${env.PUBLISH_PREFIX_PATH}/.env
                            ./src/functions/write_diary.sh
                            """
                        }
                    }

                    archiveArtifacts artifacts: "bootstrap_section/publish.json", fingerprint: true
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    withEnv([
                        'STAGE_NAME=BUILD',
                        "BUILD_BASE_DIR=${env.WORKSPACE}",
                        "TARGET_BUILD_APP=",
                        "TARGET_BUILD_OUTPUT=target"
                    ]) {
                        dir('one-press-bash') {
                            sh './src/functions/initialize_workspace.sh'
                        }
                    }

                    withEnv([
                        'STAGE_NAME=BUILD',
                        "BOOTSTRAP_BASE_DIR=${env.WORKSPACE}",
                    ]) {
                        dir('bootstrap_section') {
                            sh """
                            #!/bin/bash
                            set -e
                            ls -la
                            mv $FLOW_BOOTSTRAP_SECTION_DIR/app_source ${env.WORKSPACE}/build_section/build_app/app_source
                            ./${env.WORKSPACE}/build_section/build_app/app_source/.mvnw clean package
                            """
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs(cleanWhenNotBuilt: true,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: false)
        }
    }
}
